//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAPI.NET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAPI.NET.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;MsoNormal&quot;&gt; &lt;span style=&quot;font-size:11.0pt; font-family:&amp;quot;Calibri&amp;quot;,&amp;quot;sans-serif&amp;quot;; color:#1F497D&quot;&gt; &amp;nbsp; &lt;/span&gt;  &lt;/p&gt;
        /// &lt;p class=&quot;MsoNormal&quot;&gt; &lt;span style=&quot;font-size:11.0pt; font-family:&amp;quot;Calibri&amp;quot;,&amp;quot;sans-serif&amp;quot;; color:#1F497D&quot;&gt; &amp;nbsp; &lt;/span&gt;  &lt;/p&gt;
        ///
        /// &lt;div&gt; 
        ///
        /// &lt;div style=&quot;border:none; border-top:solid #B5C4DF 1.0pt; padding:3.0pt 0cm 0cm 0cm&quot;&gt; 
        /// &lt;p class=&quot;MsoNormal&quot;&gt; &lt;b&gt; &lt;span lang=&quot;EN-US&quot; style=&quot;font-size:10.0pt; font-family:&amp;quot;Tahoma&amp;quot;,&amp;quot;sans-ser [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmlForwardHeader {
            get {
                return ResourceManager.GetString("htmlForwardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \uc1\pard\plain\deftab360 \f0\fs20 \par
        ///\par
        ///-----Original Message-----\par
        ///From: {0} [mailto:{1}]\par
        ///Sent: {2}\par
        ///To: {3}\par
        ///Subject: {4}\par
        ///\par.
        /// </summary>
        internal static string rtfForwardHeader {
            get {
                return ResourceManager.GetString("rtfForwardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [\*\htmltag64 &lt;p class=&quot;MsoNormal&quot;&gt;]\htmlrtf [\htmlrtf0 
        ///[\*\htmltag84 &lt;span style=&quot;font-size:11.0pt; font-family:&amp;quot;Calibri&amp;quot;,&amp;quot;sans-serif&amp;quot;; color:#1F497D&quot;&gt;]\htmlrtf [\htmlrtf0 
        ///[\*\htmltag84 &amp;nbsp;]\htmlrtf \&apos;a0\htmlrtf0 
        ///[\*\htmltag92 &lt;/span&gt;]\htmlrtf ]\htmlrtf0 \htmlrtf\par]\htmlrtf0
        ///\htmlrtf \par
        ///\htmlrtf0 
        ///[\*\htmltag72 &lt;/p&gt;]
        ///[\*\htmltag0 \par ]
        ///[\*\htmltag64 &lt;p class=&quot;MsoNormal&quot;&gt;]\htmlrtf [\htmlrtf0 
        ///[\*\htmltag84 &lt;span style=&quot;font-size:11.0pt; font-family:&amp;quot;Calibri&amp;quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rtfHtmlForwardHeader {
            get {
                return ResourceManager.GetString("rtfHtmlForwardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\*\htmltag64 &lt;p class=\&quot;MsoNormal\&quot;&gt;}\htmlrtf {\htmlrtf0 
        ///{\*\htmltag84 &lt;span style=\&quot;font-size:11.0pt; font-family:&amp;quot;Calibri&amp;quot;,&amp;quot;sans-serif&amp;quot;; color:#1F497D\&quot;&gt;}\htmlrtf {\htmlrtf0 
        ///{\*\htmltag84 &amp;nbsp;}\htmlrtf \&apos;a0\htmlrtf0 
        ///{\*\htmltag92 &lt;/span&gt;}\htmlrtf }\htmlrtf0 \htmlrtf\par}\htmlrtf0
        ///\htmlrtf \par
        ///\htmlrtf0 
        ///{\*\htmltag72 &lt;/p&gt;}
        ///{\*\htmltag0 \par }
        ///{\*\htmltag64 &lt;p class=\&quot;MsoNormal\&quot;&gt;}\htmlrtf {\htmlrtf0 
        ///{\*\htmltag84 &lt;span style=\&quot;font-size:11.0pt; font-family:&amp;quot;Calibr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rtfHtmlHeader {
            get {
                return ResourceManager.GetString("rtfHtmlHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: {0} [mailto:{1}]
        ///Sent: {2}
        ///To: {3}
        ///Subject: {4}.
        /// </summary>
        internal static string textForwardHeader {
            get {
                return ResourceManager.GetString("textForwardHeader", resourceCulture);
            }
        }
    }
}
